### ISSUE TITLE
What does parameter x0y0 actually mean?

### ISSUE THREAD

**Issue by psydiot** [OGGM/oggm#1082]
Hello.I am using OGGM to explore some glaciers which I got from RGI.So I would like to clarify physical meanining of parameter x0y0 which can be found in glacier_grid.json.Does it point to the center of glacier geometry?

**Comment by jlandmann** [comment]
Hi psydiot!
Thanks for your interest in OGGM! I bumped into your question by coincidence, and I think the answer can be found in the `salem` package, since `x0y0` is an attribute of the [`Grid`](https://salem.readthedocs.io/en/stable/generated/salem.Grid.html) class there, which is serialized into a JSON file for OGGM's needs.
The salem docs say: "(x0, y0): cartesian coordinates (in proj) of the upper left or lower left corner, depending on the sign of dy".
Since OGGM uses a local tranverse mercator projection, this should mean that `x0` is the metric distance of the upper left domain corner from `lon_0` (the centroid longitude of the glacier polygon) , and `y0` is the metric distance of the upper left domain corner from the equator ("upper", as dy is negative).
Does that answer your question?
