### ISSUE TITLE
Zero or negative flux

### ISSUE THREAD

**Issue by matthiasdusch** [OGGM/oggm#1091]
When I run `inversion.prepare_for_inversion` I get a:
`RuntimeError: More than one grid point has zero or negative flux: this should not happen` error
This only happens for 1 glacier at the moment (Unterer Grindelwaldgletscher RGI60-11.01346)

Probably related to #1086 and/or #1089 but can't really wrap my head around it at the moment

MWE:
```
from oggm import cfg, utils, tasks, workflow

wd = utils.get_temp_dir()
cfg.initialize()
cfg.PATHS['working_dir'] = wd
utils.mkdir(wd, reset=True)

# does not really effect this task
# cfg.PARAMS['filter_for_neg_flux'] = True

rgis = ['RGI60-11.01346']
gdir = workflow.init_glacier_directories(rgis, from_prepro_level=3,
                                         prepro_border=10)[0]
tasks.prepare_for_inversion(gdir)
```

The error also occurs when I run all the preprocessing tasks myself.

**Comment by fmaussion** [comment]
thanks I feared this would happen. Just roll back #1089 for now, you can safely ignore it.

Or add an option in OGGM to disable this check (we will probably disable it)

**Comment by fmaussion** [comment]
OK so this happens in situations where a tributary flowline brings enough mass into a flowline to compensate for the negative flux due to mass-balance only, and so a flowline might have negative flux before the tributary.

It's really a mess to solve I think, and I need to wrap my head around it and it depends on how often it happens, etc. 

I'm going to disable the check for multiple flowlines for now.

**Comment by fmaussion** [comment]
Closed in favor of https://github.com/OGGM/oggm/issues/1093
