### ISSUE TITLE
how to get annual glacier's outlines? 

### ISSUE THREAD

**Issue by yangmin27** [OGGM/oggm#1159]

**Comment by fmaussion** [comment]
Hi @yangmin27 , thanks for your question, but it would have been nice to be a bit more polite and more precise in your request. People on github are real people working and doing their best.

If I understand your question well (and your email to me), the answer is: no, OGGM cannot provide annual outlines. Once the glaciers are treated as flowlines, they loose the capacity to represent 2D outlines of glaciers.

There have been discussions in the past to help provide such information by drawing something from the glacier flowlines, but it will be quite some work for an uncertain outcome, since the flowlines can be quite different from the real glaciers sometimes. See also https://github.com/OGGM/oggm/issues/1096 and https://github.com/OGGM/oggm/issues/1136

**Comment by yangmin27** [comment]
Dear professor,
Thank you for reply so fast... I understand now.&nbsp;
Have a good day,
Best wishes
Yangmin




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "OGGM/oggm"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月29日(星期五) 晚上7:11
收件人:&nbsp;"OGGM/oggm"<oggm@noreply.github.com&gt;;
抄送:&nbsp;"119252028"<119252028@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [OGGM/oggm] how to get annual glacier's outlines?  (#1159)





 
Hi @yangmin27 , thanks for your question, but it would have been nice to be a bit more polite and more precise in your request. People on github are real people working and doing their best.
 
If I understand your question well (and your email to me), the answer is: no, OGGM cannot provide annual outlines. Once the glaciers are treated as flowlines, they loose the capacity to represent 2D outlines of glaciers.
 
There have been discussions in the past to help provide such information by drawing something from the glacier flowlines, but it will be quite some work for an uncertain outcome, since the flowlines can be quite different from the real glaciers sometimes. See also #1096 and #1136

**Comment by fmaussion** [comment]
See also: https://github.com/OGGM/oggm/issues/1192
