### ISSUE TITLE
when I Run OGGM with GCM data example,there is something wrong

### ISSUE THREAD

**Issue by FANSCRAZY** [OGGM/oggm#1304]
when I run to "ds.volume.plot(hue='rgi_id');", It occurs: AttributeError: 'NoneType' object has no attribute 'volume'!And when I run to " workflow.execute_entity_task" It occurs: oggm.exceptions.InvalidWorkflowError: Need a valid `model_flowlines` file. If you explicitly want to use `inversion_flowlines`, set use_inversion_flowlines=True.

**Comment by Keeptg** [comment]
Hello! I suppose that you are following this [tutoral](https://oggm.org/tutorials/stable/notebooks/run_with_gcm.html), if not, please pose the link or your code here. 

I'm not sure about your environment of running OGGM. I run those code with oggm's binder test space (for both stabel and development version), and didn't encounter your problem.
If you run those code in the local environment, I'd like to suggest you check if you installed the newest oggm version first. Then, You'd like to check if you install OGGM successfully by typing and running `pytest --pyargs oggm` in your terminal.
If you are running those code in oggm's online test space like me, please let me know.

Besides, there are one more suggestion about ask questions. A good question will make people more easy to understand your problem and give you a hand. Since I'm also learning about how to ask a good question, there are [some tips](https://stackoverflow.com/help/how-to-ask#:~:text=How%20do%20I%20ask%20a%20good%20question%3F%201,may%20find%20your%20questions%20poorly-received.%20Don't%20despair!%20) I'd like to share with you. I hope that we can grow together in the way of "Ask questions". 

Finally, have fun with OGGM and github ;D
