### ISSUE TITLE
About 'oggm_netrc_credentials' command line

### ISSUE THREAD

**Issue by muzi2021** [OGGM/oggm#1370]
Can anyone explain to me how to use the command line functionality `oggm_netrc_credentials` to store my user credentials in a local `~/.netrc` file?
If someone can write a complete command line example, help me understand, I will be very grateful.

**Comment by matthiasdusch** [comment]
when you have OGGM installed under linux you should be able to start `oggm_netrc_credentials` from your shell/terminal.

Otherwise you can create a .netrc file yourself with the following content
```
machine abc.def.com
login username
password yourpassword
```
you have to replace abc.def.com, username and yourpassword obviously.
Options for abc.def.com are:

1. urs.earthdata.nasa.gov, ASTER DEM
2. geoservice.dlr.de, TanDEM-X
3. spacedata.copernicus.eu, Copernicus DEM Glo-9

And you have to create a user at these services first.

**Comment by fmaussion** [comment]
I just corrected a problem in the tool (we were testing the urs.earthdata.nasa.gov on an outdated url)

https://github.com/OGGM/oggm/pull/1372

You'll need latest oggm (development version) for this to work
