### ISSUE TITLE
cfg.PATHS['cmip5_temp_file'] needs to be removed 

### ISSUE THREAD

**Issue by yangmin27** [OGGM/oggm#1373]
Hello,
when I run GCM data, for some CMIP6 data it is fine. but when I run with CAMS-CSM1-0 datasets, it throw me an error with:
 Need to set cfg.PATHS['cmip5_temp_file']
so, How should I set this path?

**Comment by fmaussion** [comment]
This happens when the file path given to the function is None:

https://github.com/OGGM/oggm/blob/13819373b5ccf98ece0ffef0dae0c3841f979772/oggm/shop/gcm_climate.py#L302-L310

I think the fact that it doesnt work with one specific file hints at a problem in your code, e.g. that the data does not exist of something.

TODO OGGM: we should remove all ` cfg.PATHS['cmip5_temp_file']` logic and have a more useful error message here

**Comment by yangmin27** [comment]
Dear sir, 
today I run the codes again, it working without any errors now. thank you very much.
