### ISSUE TITLE
No calendar dates in compiled climate files

### ISSUE THREAD

**Issue by anoukvlug** [OGGM/oggm#1430]
Yesterday it was brought up internally, that it would be useful to have calendar dates in the compiled climate files. There are already calendar dates in the regular climates files. I can't recall why this is not the case for the compiled climate files. It might be worth to read the previous discussion on this function, before starting to add the calendar date in the `compile_climate_input()` function (e.g. PR #350, #346, ...).

**Comment by JordiBolibar** [comment]
I was taking a look at this today, and it is indeed quite annoying, since the conversion to decimal years is lossy, so there's no clean way to recover the original dates. 

From my naive point of view, this fix looks extremely simple. Just removing [this line](https://github.com/OGGM/oggm/blob/157c44b5b63c2a848ffb318afe77da4a18223a0d/oggm/utils/_workflow.py#L1333) and keeping the original datetime format might do the trick.

**Comment by fmaussion** [comment]
> I was taking a look at this today, and it is indeed quite annoying, since the conversion to decimal years is lossy, so there's no clean way to recover the original dates.

There should not be such an issue - we work with this system since a long time, maybe something went wrong in the netcdf storage. I'll have a look, I'm sure we can have them easily.

> From my naive point of view, this fix looks extremely simple. Just removing [this line](https://github.com/OGGM/oggm/blob/157c44b5b63c2a848ffb318afe77da4a18223a0d/oggm/utils/_workflow.py#L1333) and keeping the original datetime format might do the trick.

There is a reason we don't use datetime formats internally for OGGM output: mostly for compatibility with GCM data which has all kinds of calendar (365 no leap mostly), and to allow for idealized dates (e.g. [0 - 100]). For for these data we can add a timestamp

**Comment by fmaussion** [comment]
tbh I'm not sure what we are talking about here :smile: 

Compiled climate files do have the dates in them:

![image](https://user-images.githubusercontent.com/10050469/176482667-d96b3fa5-3896-4520-a5af-bce636b6ea41.png)

For example groupby:

![image](https://user-images.githubusercontent.com/10050469/176483036-232a2225-54d5-4d71-95d8-2191ab9efc0f.png)

We can continue this discussion on slack maybe

**Comment by anoukvlug** [comment]
I agree.

I think I misunderstood the issue earlier. I thought you meant calendar dates, as in day-month-year (and e.g. a days since timestamp) not year-month.

**Comment by fmaussion** [comment]
feel free to reopen if needed!
