### ISSUE TITLE
Questions about the results of OGGM simulations of future glacier evolution.

### ISSUE THREAD

**Issue by KReeves092** [OGGM/oggm#1497]
I simulate the evolution (including area and volume) of a mountain glacier (RGI60-10.00604) located in North Asia under four climate scenarios (SSP126, SSP245, SSP370, SSP585) according to the OGGM tutorial. The details are shown in the figure below.
![Area](https://user-images.githubusercontent.com/106970767/196042875-a9ce97b1-05dd-4f27-855f-082feb130ad7.png)![Volume](https://user-images.githubusercontent.com/106970767/196042907-561def33-2db8-4bb8-b903-023e00e2ac99.png)
The results show that glacier area and volume are decreasing under all four climate scenarios, but there is an abrupt change in the rate of glacier area change compared to the change in glacier volume. In 2059-2075, the rate of glacier area reduction increases instantaneously for the four climate scenarios, while the glacier volume change curve is relatively smooth for 2020-2099.
I would like to ask what are the reasons for such simulation results?

**Comment by anoukvlug** [comment]
I guess it's due to the geometry. (e.g. there might be a relatively large part of the lower lying part of the glacier where the ice isn't very thick and the glacier ice disappears around the same time.)
You could use the following [tutorial](https://oggm.org/tutorials/stable/notebooks/where_are_the_flowlines.html#flowline-geometry-after-a-run-with-filemodel) as inspiration for having a more close look at your output.
