### ISSUE TITLE
Calibration with custom climate issue

### ISSUE THREAD

**Issue by duiliofg** [OGGM/oggm#1586]
[OGGM 1.6]

Hi, 

I need some help, I'm using a custom glacier inventory and a custom Climate baseline. When I run this command: 

`ref_mb_years = [2001, 2021]
gdir=gdirs[5]
ref_mb=float(ref_mb21.loc[juncal.rgi_id])
print(ref_mb)
mb_calibration_from_scalar_mb(gdir, ref_mb=ref_mb,
                              ref_mb_years=ref_mb_years, # 
                              overwrite_gdir=True,
                              );`

I'm getting this 

`InvalidWorkflowError: prcp_fac from_winter_prcp is only compatible with the W5E5 climate dataset!` 

How can I solve it ? thank you.

my cfg setting:
cfg.initialize(logging_level='ERROR') 
cfg.PARAMS['use_multiprocessing'] = True
cfg.PARAMS['use_rgi_area'] = False
cfg.PARAMS['use_intersects'] = False
cfg.PATHS['working_dir'] = utils.gettempdir(dirname='juncal_sur', reset=True)
cfg.PARAMS['border']               = 80
cfg.PARAMS['min_mu_star']          = 5
cfg.PARAMS['max_mu_star']          = 600
cfg.PARAMS['geodetic_mb_period']   = '2001-01-01_2021-01-01' 
cfg.PARAMS['store_model_geometry'] = True
cfg.PARAMS['continue_on_error']    = True
cfg.PARAMS['baseline_climate']='CUSTOM'
cfg.PARAMS['use_winter_prcp_factor'] = False
#cfg.PARAMS['prcp_scaling_factor']  = 1

Update
By the way... now I'm working with a bypass, I'm just changing the cfg.PARAMS['baseline_climate']="W5E5".  But I'm not sure if this could affect the result.

**Comment by lilianschuster** [comment]
Hi @duiliofg,
If I understand it correctly, you use a baseline climate which is different to W5E5. So, it is correct to do `cfg.PARAMS['baseline_climate']='CUSTOM'`  and `cfg.PARAMS['use_winter_prcp_factor'] = False`. However, you also need to set the precipitation factor (i.e. cfg.PARAMS['prcp_fac'] or you directly change `prcp_fac` in the `mb_calibration_from_scalar_mb` function, see the code inside of the function: https://github.com/OGGM/oggm/blob/01cba8b59ced6715111d937a8c5554b53d18227b/oggm/core/massbalance.py#L1741 ) .
 Which precipitation factor to choose depends on how your climate dataset looks like. If you have further data available, for that glacier (e.g. in-situ direct glaciological MB data), you can calibrate the precipitation factor to match e.g. the interannual MB variability. Otherwise, you can use for the beginning a factor of 2, and then use a factor of 1 & 3 to see the differences. 
In this tutorial (https://oggm.org/tutorials/stable/notebooks/advanced/massbalance_calibration.html#overparameteristion-or-the-magic-choice-of-the-best-calibration-option)  you can see how you can do that and you also see how the prcp. fac influences e.g. the annual MB changes.

**Comment by duiliofg** [comment]
Great, thank you very much I'll try that.

**Comment by Cly-art** [comment]
Hi, I also could not deal with the problem. Do you solve it?
Thanks!

**Comment by anoukvlug** [comment]
@Cly-art, this issue appears to have been solved, as the the person who raised the question has closed it as completed. 

Without knowing the precise issue you're encountering, I can't really help you further. Either way here is a link to the [error guide blog post](https://oggm.org/2023/11/02/error-guide/). Joining the [OGGM slack](https://oggm.org/2022/10/11/Welcome-to-the-OGGM-Slack/), our internal communications platform, might also be useful to you when actively using the model.

**Comment by Cly-art** [comment]
> @Cly-art, this issue appears to have been solved, as the the person who raised the question has closed it as completed.
> 
> Without knowing the precise issue you're encountering, I can't really help you further. Either way here is a link to the [error guide blog post](https://oggm.org/2023/11/02/error-guide/). Joining the [OGGM slack](https://oggm.org/2022/10/11/Welcome-to-the-OGGM-Slack/), our internal communications platform, might also be useful to you when actively using the model.

ok! thanks a lot!
