### ISSUE TITLE
Shift in coordinates of gridded_data and dem.tif

### ISSUE THREAD

**Issue by pat-schmitt** [OGGM/oggm#1679]
From my understanding, when you do `tasks.gridded_data_var_to_geotiff(gdir, 'topo')` the resulting file `topo.tif` should be exactly the same as `dem.tif`. However, when you look at the two files (e.g. in QGIS) you see that they are shifted by half a pixel.

I will add a test for this and try to find the problem in the next few days. This probably also needs to be considered in PR https://github.com/OGGM/oggm/pull/1674.

**Comment by fmaussion** [comment]
the culprit is probably here: 

https://github.com/OGGM/oggm/blob/6e0fb56d92f02aa525e71daeee9be4848c81b5e5/oggm/core/gis.py#L1686 

We have to ask Salem to provide the corner coordinates, with grid.corner_grid: https://salem.readthedocs.io/en/stable/generated/salem.Grid.corner_grid.html#salem.Grid.corner_grid
