### ISSUE TITLE
oggm.core.dynamic_spinup: RuntimeError occurred during task run_dynamic_spinup_spinup_dynamic_area

### ISSUE THREAD

**Issue by Nicole1150** [OGGM/oggm#1688]
oggm.core.dynamic_spinup: No dynamic spinup could be conducted and the original model with no spinup is saved using the provided output_filesuffix "_spinup_dynamic_area". The error message of the dynamic spinup is: Could not find mismatch smaller 1% (only 1.2161631618661213%) in 30Iterations!
2024-02-27 17:16:03: oggm.core.dynamic_spinup: RuntimeError occurred during task run_dynamic_spinup_spinup_dynamic_area on RGI60-13.44477: Could not find mismatch smaller 1% (only 1.2161631618661213%) in 30Iterations!
Error occurred for glacier RGI60-13.44477: Could not find mismatch smaller 1% (only 1.2161631618661213%) in 30Iterations!

oggm.core.dynamic_spinup: No dynamic spinup could be conducted and the original model with no spinup is saved using the provided output_filesuffix "_spinup_dynamic_area". The error message of the dynamic spinup is: Not able to minimise! Problem is unknown, need to check by hand! Best mismatch 6.491358458590482%
2024-02-27 17:38:13: oggm.core.dynamic_spinup: RuntimeError occurred during task run_dynamic_spinup_spinup_dynamic_area on RGI60-13.44741: Not able to minimise! Problem is unknown, need to check by hand! Best mismatch 6.491358458590482%
Error occurred for glacier RGI60-13.44741: Not able to minimise! Problem is unknown, need to check by hand! Best mismatch 6.491358458590482%

**Comment by pat-schmitt** [comment]
Hi, simply posting an error message without any context is not sufficient for us to provide help. Here's a blog post that outlines steps to take if you encounter difficulties while using OGGM: https://oggm.org/2023/11/02/error-guide/.

Additionally, since your question pertains to using OGGM rather than a bug within the code, you might want to consider joining our Slack channel. On this platform we offer support on how to use OGGM, and you can also search through previous posts to find answers. Here's a blog post with instructions on how to join the OGGM Slack community: https://oggm.org/2022/10/11/Welcome-to-the-OGGM-Slack/.
