### ISSUE TITLE
Appveyor builds are broken (again)

### ISSUE THREAD

**Issue by fmaussion** [OGGM/oggm#286]
https://ci.appveyor.com/project/fmaussion/oggm/build/1.0.743 

cc @TimoRoth just in case you have an idea...

**Comment by TimoRoth** [comment]
Yes, I have seen that too for a while now. And I have absolutely no idea what is going wrong.
It looks like conda itself is just plain broken.

**Comment by fmaussion** [comment]
Should we just drop CI on appveyor? 

It bothers me a little to do so, but experience shows that 99% of the problems aren't related to OGGM, but always to some installation issues...

**Comment by TimoRoth** [comment]
I'll have a look at what's going wrong there, and if I can't figure it out soon enough, that might be for the better for now.

**Comment by TimoRoth** [comment]
The error seems to be caused by pytest switching to noarch builds:
https://github.com/conda-forge/pytest-feedstock/issues/24
Using a recent enough conda should work just fine, and we are by default using the very latest one, so I'm not sure what's happening, but we aren't the only ones affected, and it's an issue with either the pytest build or a bug in conda.

**Comment by fmaussion** [comment]
closed via https://github.com/OGGM/oggm/pull/287
