### ISSUE TITLE
FileNotFoundError for RGI50-07 region during CRU processing

### ISSUE THREAD

**Issue by sumnonpuella** [OGGM/oggm#335]
I'm getting an error during `tasks.compute_ref_t_stars()`, running it with the gdirs from the RGI50-07 region (Svalbard). The error messages is: 
`FileNotFoundError: [Errno 2] No such file or directory: '/home/david/OGGM_WORKING_DIRECTORY/per_glacier/RGI50-07/RGI50-07.00/RGI50-07.00231/climate_info.pkl'`

I went back and looked at the log output for the `process_cru_data` for RGI50-07.00231, and found the error:
`017-10-25 16:49:35: oggm.core.preprocessing.climate: (RGI50-07.00232) process_cru_data
2017-10-25 16:49:35: oggm.core.preprocessing.climate: OSError occurred during task process_cru_data on RGI50-07.00222!
2017-10-25 16:49:35: oggm.core.preprocessing.climate: OSError occurred during task process_cru_data on RGI50-07.00223!`

I looked in the glacier directory at the log, and it says there was an OSError: NetCDF: HDF error. I haven't had this problem with other regions. I'm still fairly new to this, and i'm not sure where to start looking for solutions.

**Comment by fmaussion** [comment]
I've seen this ``OSError: NetCDF: HDF error`` happening from time to time, but I've not been able to always reproduce them. Maybe it's a temporary I/O failure or something, because this should work. Maybe trying to reset this one directory could help.

Note that it's not necessary to compute the reference t* yourself. For default set-ups I'd recommend the method described here: http://oggm.readthedocs.io/en/latest/run_examples/run_from_calibrated.html 

I have an idea of how to make this step even simpler, I might make an improvement to this system in the next couple of days

**Comment by fmaussion** [comment]
For example, this just happened to me too: in this case, the CRU CL file (downloaded automatically from the oggm-sample-data repo) was corrupted for some obscure reason. I re-downloaded the file and it was good. 

This is quite annoying indeed, but I'm not sure there is something we can do about it.

**Comment by fmaussion** [comment]
Using precalibrated t* is now the default in OGGM see: http://oggm.readthedocs.io/en/latest/run_examples/run_from_calibrated.html

(PR: https://github.com/OGGM/oggm/pull/338)

**Comment by sumnonpuella** [comment]
It's working fine now. Thanks!
