### ISSUE TITLE
CCSM processed data format

### ISSUE THREAD

**Issue by sumnonpuella** [OGGM/oggm#353]
I'm working on getting OGGM running with specific version of CCSM3 data. Reformatting `process_cesm_data` has worked for the most part, but I'm struggling to get the time dimension properly formatted in the returned netCDF file. Is there an processed `cesm_data.nc` file I could look at somewhere to get an idea of the necessary structure? Should it be identical to `climate_monthly.nc`? Any other recommendations for dealing with problems getting the time dimension to agree with the model? Thanks!

**Comment by fmaussion** [comment]
Hi Schmitty, I'd recommend to have a look at this test: https://github.com/OGGM/oggm/blob/master/oggm/tests/test_prepro.py#L1877 Here we use standard CESM files to generate a processed `cesm_data.nc`. I'd also recommend to write a similar test for your code, too.

Note that we should consider adding your task to the OGGM codebase, since this would be a useful addition.
