### ISSUE TITLE
Time change in PastMassBalance model

### ISSUE THREAD

**Issue by sumnonpuella** [OGGM/oggm#359]
I'm getting odd errors trying to use the PastMassBalance model with a custom climate data. The input climate file has 12 months of data (October 1950 - September 1951). When I try to run until equilibrium, the model is searching for years that aren't there. With y0=1950, 

`mb = mbmods.PastMassBalance(gdir, filename='cesm_data')`
`model_fls = gdir.read_pickle('model_flowlines')`
`model = FluxBasedModel(model_fls, mb_model=mb, y0=1950, time_stepping='default')`
`model.run_until_equilibrium()`
`ValueError: Year 1950.0 not in record`

and with y0 = 1951,

`model = FluxBasedModel(model_fls, mb_model=mb, y0=1951, time_stepping='default')`
`model.run_until_equilibrium()`
`ValueError: Year 1952.013698630137 not in record`.

I looked at the times stored in `mb`, and the time stored in the model doesn't match up with the input file. 

`self.years = [1951, 1951, 1951, 1951, 1951, 1951, 1951, 1951, 1951, 1951, 1951,
       1951]`
`self.months = [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]`

It looks like this time is switched in PastMassBalance (line 243).

`# This is where we switch to hydro float year format`
`# Last year gives the tone of the hydro year`
`self.years = np.repeat(np.arange(time[-1].year-ny+1, time[-1].year+1), 12)`
`self.months = np.tile(np.arange(1, 13), ny)`

Is this a bug in OGGM, or do I need to set up the mass balance model differently? I can try to adjust PastMassBalance to store the correct dates if need be.

**Comment by fmaussion** [comment]
Thanks for the report!

I think I understand a bit better what's going on. 

First (and this is the most important), `run_until_equilibrium` and `PastMassBalance` are not going to work well together (even with CRU data).  `run_until_equilibrium` is a utility function which runs the model until the glacier volume doesn't change any more (according to a predefined threshold). That is, it's going to need decades (up to centuries) depending on the size of the glacier. `run_until_equilibrium` was meant to be used with constant mass-balances only, i.e. with the [`ConstantMassBalance`](https://github.com/OGGM/oggm/blob/master/oggm/core/massbalance.py#L311) model. Now, I see that the `ConstantMassBalance` class lacks keyword arguments in order to read alternative climate input files (i.e. it reads CRU per default and only CRU). Fortunately, this is going to be quite easy to add by adding the right kwargs and pass them to the internal [PastMassBalance](https://github.com/OGGM/oggm/blob/master/oggm/core/massbalance.py#L200-L204).

Then, you say:
> I looked at the times stored in mb, and the time stored in the model doesn't match up with the input file.

This is by design and was discussed recently (https://github.com/OGGM/oggm/issues/348 and https://github.com/OGGM/oggm/pull/352). The core idea is that the actual climate data is stored with real, calendar dates but that the model uses a "floating year" convention, with the year 1951, month 1 being the start of the hydrological year. I.e. this here:
```python
years = [1951, 1951, 1951, 1951, 1951, 1951, 1951, 1951, 1951, 1951, 1951, 1951]
months = [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
```
is correct according to the model design. What I would like to do very soon though is to make the definition of the hydrological year more flexible. I will try to do this by tomorrow.

In the mean time, try to have a look at point 1 above and let me know if my explanation is clear enough. A PR would be welcome, but if you have no time I can have a look myself.

**Comment by sumnonpuella** [comment]
Thanks for the advice, everything is very clear. I'll work on `ConstantMassBalance` and try for a PR in the next few days.

**Comment by sumnonpuella** [comment]
The changes to `ConstantMassBalance` work great! Should I open up a PR?

**Comment by fmaussion** [comment]
Yes, absolutely! Thanks

**Comment by sumnonpuella** [comment]
@fmaussion with the change you suggested in PR #362, I'm still getting the same error. I tried changing the `halfsize` parameter of `ConstantMassBalance` to 0.5, but it keeps searching for years that don't exist. For example, 

`mb = mbmods.ConstantMassBalance(gdir, y0=1951.5, halfsize=0.5, filename='cesm_data')`
`mb.years`
`(array([ 1951.,  1952.])`
`fls = gdir.read_pickle('model_flowlines')`
`model = FluxBasedModel(fls, mb_model=mb, y0=1951, time_stepping='default')`
`model.run_until_equilibrium()`
`ValueError: Year 1952 not in record`

Are there any changes I could make to `ConstantMassBalance`, or are there any parameter changes that might help.

**Comment by sumnonpuella** [comment]
That works - thank you so much for your help.

**Comment by fmaussion** [comment]
Would you like to add all this to your PR?

**Comment by sumnonpuella** [comment]
Yes! I'll add it in and submit it tonight.
