### ISSUE TITLE
SRTM download-links are dead

### ISSUE THREAD

**Issue by matthiasdusch** [OGGM/oggm#504]
The url to download SRTM topo-files within `oggm.utils._download_srtm_file_unlocked` seems to be deprecated.

See for example: http://droppr.org/srtm/v4.1/6_5x5_TIFs/srtm_06_01.zip

Possible fixes:
a) Find open access and reliable 3rd party download source
b) Host all files on our own
c) Get them directly from USGS (I think this needs an account)

For c) [usgs api](https://mapbox.github.io/usgs/index.html) might be useful.

**Comment by DavidParkes** [comment]
I had an issue with this (through an extra layer of indirection) and just replaced the line as follows:

wwwfile = 'http://srtm.csi.cgiar.org/SRT-ZIP/SRTM_V41/SRTM_Data_GeoTiff/srtm_' + zone + '.zip'

Everything worked from there. I don't know what the 'correct' way to go about this is though.

**Comment by DavidParkes** [comment]
I don't fully understand github yet, and I know that my local copy of that file was already different in at least one (albeit trivial) aspect to the master, so it might be quicker for someone else (I guess you - sorry!) to make that change as it's such a small fix that can block the functioning of the whole program.

Sorting myself out with a properly version-managed repository and understanding the exact nature of version management here are on my task list for the week!

**Comment by fmaussion** [comment]
Interesting. I really don't remember from where I got this droppr base url from, but we definitely should go back to the official repo: http://srtm.csi.cgiar.org/SELECTION/inputCoord.asp

I wonder if they used droppr as a temporary solution and now provide the data themselves.

If we do so we should definitely inform @TimoRoth because the url in the cluster's cache has to be updated too (ideally I would even redownload the entire dataset, just to be sure)

**Comment by matthiasdusch** [comment]
I opened PR #505 

There are tests in place, but they do not download the file if it already exists locally. This is probably true for every download-test and should hence be addressed in a more general fashion.
