### ISSUE TITLE
 AttributeError: module 'oggm.cfg' has no attribute 'A'

### ISSUE THREAD

**Issue by egalistmir** [OGGM/oggm#530]
I just tested the case study "historical run from a liquid glacier"
when I typed in "glen_a = cfg.A*2"
there is an AttributeError: module 'oggm.cfg' has no attribute 'A'
After understadning the meaning of A (ice creep parameter),
I found the attribute 'A' from the script named params.cfg
glen_a = 2.4e-24
so the attribute A is 2.4e-24， right?
maybe the attribute A need be added into the cfg.

**Comment by phigre** [comment]
Hi,
I wasn't involved in the latest pull request, but there were some changes, also to this parameter.
Replacing
`cfg.A`
by
`cfg.PARAMS['glen_a']`
should work with the newest version of OGGM.
See also the [whats-new.rst](https://github.com/OGGM/oggm/blob/master/docs/whats-new.rst):
> The ice dynamics parameters (Glen A, N, ice density) are now "real" parameters accessible via cfg.PARAMS (:pull:`520`, :issue:`511` and :issue:`27`). Previously, they were also accessible via a module attribute in cfg, which was more confusing than helping.

Indeed, the default value for A / glen_a is 2.4e-24 as you said.

Hope this helps,
Philipp

**Comment by fmaussion** [comment]
Hi @egalistmir , can you let us know if you have been able to solve your problem? 

In a recent commit I decided to remove the variable ``cfg.A`` in favor of the parameter ``glen_a`` in ``params.cfg``: https://github.com/OGGM/oggm/blob/44558012e0a34582706ca162e774e58ee8b06e18/oggm/params.cfg#L188 

From your code you can access it with: ``cfg.PARAMS['glen_a']`` as @phigre points out.

I will make one more change to the model until OGGM v1.1 is out (very soon, since the review of our GMD paper is positive), but after this we will be much more conservative in the changes we make to the codebase.

**Comment by egalistmir** [comment]
Hi Maussion，
     Yes, I have solved the problem. Thank you very much. I am using the OGGM version 1.1 to simulate some glaciers in the west Tibet.
