### ISSUE TITLE
Bring HCL to OGGM

### ISSUE THREAD

**Issue by fmaussion** [OGGM/oggm#548]
With the release of [python-colorspace](https://python-colorspace.readthedocs.io), we now have a way to use expertly created colormaps in OGGM. 

We should replace the existing colors (which are meh) with nice ones!

**Comment by sadielbartholomew** [comment]
Is anybody in the process of implementing this or can I give it go? Thanks.

**Comment by fmaussion** [comment]
Hi @sadielbartholomew - I didn't expect anyone out of the OGGM community to tackle this one, but if you'd like to do it (and have a good taste for colors ;), please go for it!

I expect this to be quite an easy change, but the hard part will be to actually choose colors which are nice and expressive. Basically all graphics functions are located in `oggm.graphics` and share a common basis - the code is a bit quick and dirty but all functions can be tested with `pytest --mpl oggm/tests/test_graphics` (from the oggm root repository).

**Comment by fmaussion** [comment]
Here are the sample images created by the tests: https://github.com/OGGM/oggm-sample-data/tree/master/baseline_images/freetype_28

**Comment by sadielbartholomew** [comment]
Hi, sorry I assumed it was open for anyone given the 'Hacktober' tag.

I'll have a look & try to produce sets of colours which look nice. If I can I will put in a PR. Though 'nice' is a matter of taste, so others may not agree on what looks good!

Thank you very much for the pointers.

**Comment by fmaussion** [comment]
> Hi, sorry I assumed it was open for anyone given the 'Hacktober' tag.

It is open to anyone! It's just that OGGM is a very specialized project, i.e. unlikely to attract non-glaciologists. Which doesn't mean that you shouldn't try ;)

**Comment by sadielbartholomew** [comment]
Unfortunately, I have so far been unable to install OGGM, despite having followed the instructions under 'Installing OGGM' in the sphinx docs step-by-step, and tried various debugging steps by consulting related open & closed issues.

It relates to geopandas, fiona &./or libncurses. I am using Ubuntu 16.04 (64-bit). The full traceback is:

```
ImportError while loading conftest '/home/vagrant/oggm/oggm/conftest.py'.
__init__.py:30: in <module>
    from oggm.utils import (GlacierDirectory, entity_task, global_task,
utils.py:30: in <module>
    import geopandas as gpd
../../miniconda3/envs/oggm_env/lib/python3.6/site-packages/geopandas/__init__.py:4: in <module>
    from geopandas.io.file import read_file
../../miniconda3/envs/oggm_env/lib/python3.6/site-packages/geopandas/io/file.py:3: in <module>
    import fiona
../../miniconda3/envs/oggm_env/lib/python3.6/site-packages/fiona/__init__.py:69: in <module>
    from fiona.collection import Collection, BytesCollection, vsi_path
../../miniconda3/envs/oggm_env/lib/python3.6/site-packages/fiona/collection.py:9: in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
E   ImportError: libncurses.so.6: cannot open shared object file: No such file or directory
```

I have tried removing 'defaults' as a conda-forge channel as suggested [here](https://github.com/conda-forge/geopandas-feedstock/issues/44#issuecomment-418733330) so that ``conda config --show`` item just has:

```
channels:
  - conda-forge
  - oggm
```
& various other changes without avail. I did not do any subsequent installations or upgrades; nothing except run the commands in the instructions. Do you know what could be causing this?

In the meantime, as I have by now looked over that page a number of times in detail, I have spotted a number of minor issues with that page, so I have put in a PR (#584) to amend those. I hope that is okay - it's 'low hanging fruit' as a PR, but I thought I might as well quickly fix what I noticed.

**Comment by TimoRoth** [comment]
An up to date conda installation (create -n oggm_env -c oggm -c conda-forge python=3.7 && conda install -c oggm -c conda-forge oggm-deps) should bring you to a state where tests at least run. Right now the latest updates seem to have broken some tests, primarily due to minimal changes in the image comparisons.
