### ISSUE TITLE
Add some data in inversion_input.plk

### ISSUE THREAD

**Issue by Keeptg** [OGGM/oggm#708]
Hello,
I want to calculate the area/max_hight/min_hight of each catchment and put them in `inversion_input.plk`, so I add the following code in `oggm.core.centerlines.py`(in `def catchment_area(gdir):`after line:1481):
`max_h = []`
 `min_h = []`
 `catchment_area = []`
 `for cl_catch in cl_catchments:`
 `    # Search the max/min hight value in topo data`
 `    max_h.append(np.max(topo[tuple(cl_catch.T)]))`
 `    min_h.append(np.min(topo[tuple(cl_catch.T)]))`
 `    # Count grid numbers of each catchment and calculate their area`
 `    catchment_area.append(abs(len(cl_catch)*gdir.grid.dx*gdir.grid.dy))`
 `geom['max_h'] = max_h`
 `geom['min_h'] = min_h`
 `geom['catchment_area'] = catchment_area`
It works, but the sum areas I got do not match with the polygon_area very well, is there more effective method to achieve my goal?
Besides, I also want to calculate the length of each centerline or flowline and put them in the `inversion_input.pkl`, is there any suggestion or simple way to do this?
Any suggestions or answers will be great.
Thanks.

**Comment by fmaussion** [comment]
> It works, but the sum areas I got do not match with the polygon_area very well, is there more effective method to achieve my goal?

Without knowing what "very well" means, it's quite hard to answer. But a certain difference is expected because of the difference between "true" area and the raster (grid) mask of the glacier. In the flowline representation of the glacier, we assume that the RGI Area is the pure reference and correct for this, i.e. here: 

https://github.com/OGGM/oggm/blob/4724ced7a1394d2dc1ee14a91c39000a35440475/oggm/core/centerlines.py#L1877-L1886

> Besides, I also want to calculate the length of each centerline or flowline and put them in the `inversion_input.pkl`, is there any suggestion or simple way to do this?

`fl.nx * fl.dx * gdir.grid.dx` should give you the length in meters.

May I ask why you want to do this? It might be worth adding a simple separate "flowline diagnostics" task either directly in OGGM or somewhere in your code, instead of modifying OGGM core itself (otherwise you'll eventually get in trouble when trying to update).

**Comment by matthiasdusch** [comment]
> It works, but the sum areas I got do not match with the polygon_area very well, is there more effective method to achieve my goal?

I just tested this for a couple of glaciers and got `gdir.rgi_are_m2 / sum(catchment_area) = 0.92-0.98` which seems reasonable as you compare a polygon outline with one which got smoothed and then converted to a gridded raster mask. The bigger the glacier the smaller the error.

**Comment by Keeptg** [comment]
> otherwise you'll eventually get in trouble when trying to update.
Thanks for your good advice and kind remind. I will do some retries tomorrow.
I want use those data to do some test, see if there any chance to improve another ice thickness inversion model named Glabtop.

**Comment by Keeptg** [comment]
> May I ask why you want to do this? It might be worth adding a simple separate "flowline diagnostics" task either directly in OGGM or somewhere in your code, instead of modifying OGGM core itself (otherwise you'll eventually get in trouble when trying to update).

Thanks for your good advice and kind remind. I will do some retries tomorrow.
I want use those data to do some test, see if there any chance to improve another ice thickness inversion model named Glabtop

**Comment by Keeptg** [comment]
> I just tested this for a couple of glaciers and got `gdir.rgi_are_m2 / sum(catchment_area) = 0.92-0.98` which seems reasonable as you compare a polygon outline with one which got smoothed and then converted to a gridded raster mask. The bigger the glacier the smaller the error.

Thanks, @fmaussion 's corrective plan seems wonderful. I will do more test in this.

**Comment by matthiasdusch** [comment]
if questions arise along the way, feel free to ask here

**Comment by Keeptg** [comment]
> if questions arise along the way, feel free to ask here

Thanks for your kindness : )

**Comment by Keeptg** [comment]
>  for fl in fls: 
>      area += np.sum(fl.widths) * fl.dx 
>   

I do some simple tests in morning. 
I used both `catchment_indices`'s points number and fl.dx(in inversion_flowlines.pkl) calculate the catchment area. All of them got similar sum area, but for each individual catchment, the result seems very different. The following list is my results. The first column
got from `fl.dx` method and the second column got from `catchment_indices`

_catchment_area_fls      catchment_area_geo
      7514507.71                 15080000.00
    15125134.51                 24600000.00
    28095180.64                 32160000.00
     3916398.46                  6920000.00
    20070375.53                 22800000.00
    18255582.53                 22000000.00
    17510911.89                 33280000.00
    10254807.73                 13000000.00
    10786902.98                 14400000.00
     6042655.42                  15320000.00
   112900693.86                103000000.00
    33913771.86                 32920000.00
    24409665.87                 20280000.00
    32023776.37                 32680000.00
   124634776.13                118600000.00
   224703858.50                191920000.00_
Did I misunderstand the meaning of `np.sum(fl.widths) * fl.dx * gdir.grid.dx**2`?
And here is my code:
`    fpath = gdir.get_filepath('gridded_data')`
`    geom = gdir.read_pickle('geometries')`
`    catchment_ids = geom['catchment_indices']`
`    tasks.prepare_for_inversion(gdir)`
`    inversion_inputs = gdir.read_pickle('inversion_input')`
`    fls = gdir.read_pickle('inversion_flowlines')`
`    max_h = []`
`    min_h = []`
`    towrite = []`
``
`    with utils.ncDataset(fpath) as nc:`
`        topo = nc.variables['topo_smoothed'][:]`
``
`    for pet in catchment_ids:`
`        max_h.append(np.max(topo[tuple(pet.T)]))`
`        min_h.append(np.min(topo[tuple(pet.T)]))`
``
`    for pet, inputs in enumerate(inversion_inputs):`
`        length = fls[pet].nx * fls[pet].dx * gdir.grid.dx`
`        catchment_area_fls = np.sum(fls[pet].widths) * fls[pet].dx * gdir.grid.dx**2`
`        catchment_area_geo =len(geom['catchment_indices'][pet]) * gdir.grid.dx**2`
`        inputs['length'] = length`
`        inputs['catchment_area_fls'] = catchment_area_fls`
`        inputs['catchment_area_geo'] = catchment_area_geo`
`        inputs['max_h'] = max_h[pet]`
`        inputs['min_h'] = min_h[pet]`
`        towrite.append(inputs)`
``
`    gdir.write_pickle(towrite, 'inversion_input')`

**Comment by matthiasdusch** [comment]
Hi, first of all thanks for the minimal working example. This makes it much easier to respond!

Second: I find the flowline width calculation and correction a bit confusing myself. So don't take all I say for granted and maybe @fmaussion can point out possible errors. But he's quite busy the next days, so ...

In the way it is calculated in `centerlines.catchment_width_correction` there is a difference between the area of the actual catchment (what you call `catchment_area_geo`) and the area which each flowline represents: The flowline does not necessarily span the whole catchment area as lines flowing into other lines are cut short before the individual junction.
Perhaps this is best explained on the two attached plots. The first shows the different catchment areas along the calculated **Centerlines**. Those lines and the catchment areas actually touch the next Centerline. 
The second plot shows the **Inversion Flowlines** with their respective widths sections. They do not touch their subsequent line.

![catchement_areas](https://user-images.githubusercontent.com/37663627/53650903-e0985380-3c45-11e9-9d8d-ecbffc47542c.png)

![flowlines](https://user-images.githubusercontent.com/37663627/53650907-e3934400-3c45-11e9-8478-fdf596337075.png)


Also: If you look at the area ratio (area_geo/area_fls like you calculated it) you will find that this is largest (up to 2.6 in the example above) for those lines of lower order (an order 0 flowline does not receive any inflow from other lines. E.g all the small catchments on the boundary of the glacier above. In contrast the main flowline always has the highest order). 
Higher order flowlines area ratio is closer to 1, between 0.86 and 1.02 in this example.

**Comment by Keeptg** [comment]
@matthiasdusch ,

Thanks very much for your detailed and patient response!

**Comment by fmaussion** [comment]
Unfortunately I can't have a look at your code right now, but there is at least three reasons why the area of the 2D catchment (the one obtained with ``catchment_indices``) is not always the same as the one from the flowline widths:

1. In [catchment_width_correction](https://github.com/OGGM/oggm/blob/f0768d867ca39dce6d605214591d76696bc88553/oggm/core/centerlines.py#L1744), arguably one of the most complex and less elegant task of OGGM :roll_eyes: , I had to transfer some area to downstream catchments. This happens when the lowest grid point on the flowline is higher than parts of the catchment; in this case the area is transferred downstream:

https://github.com/OGGM/oggm/blob/f0768d867ca39dce6d605214591d76696bc88553/oggm/core/centerlines.py#L1854-L1861

2. I also smoothed the flowlines, an operation which is not area-conservative:

https://github.com/OGGM/oggm/blob/f0768d867ca39dce6d605214591d76696bc88553/oggm/core/centerlines.py#L1863-L1872

(here again, this choice is very arguable - Huss & Farinotti 2012, and Huss 2015 model do not smooth)

3. We bulk correct for the final glacier area to be equal to the RGI area 

Taken together, this might make some difference. But I'll try to have a look at your code when time permits.

However, if I understand your use case well, what you probably want to use is the area computed with ``catchment_indices``. Note also that we had similar discussions with @MatCast about whether or not the catchments are a good indicator for glacier thickness. In theory it must be, but sometimes the catchment are not well defined (like in your case), and they lead to discontinuities in the 2D field (which you will have to account for in your model).

I all cases, this is the right moment to add the necessary tools to OGGM. I suggest to create new separate task(s) for these kind of diagnostic tools, and try to write all of them at once. The code written by @MatCast could be a good starting point, and then we can add diagnostics for @Keeptg as well.

**Comment by Keeptg** [comment]
@fmaussion ,
Thanks very much! I'll keep wathcing this.

**Comment by fmaussion** [comment]
@Keeptg in case you didn't notice. We recently added new gridded data attributes than can be useful for glacier thickness modelling: https://github.com/OGGM/oggm/pull/725 

In particular, you might want to have a look at the new tutorial: https://mybinder.org/v2/gh/OGGM/oggm-edu/master?urlpath=lab/tree/notebooks/oggm-tuto/thickness_model.ipynb 

Cheers!

**Comment by fmaussion** [comment]
I'm closing this now, let us now if there are still unclear things
