### ISSUE TITLE
compile files naming

### ISSUE THREAD

**Issue by anoukvlug** [OGGM/oggm#752]
As the complied files are by default placed in the` cfg.PATHS['working_dir']` the files get overwritten when you compile more than one region by region. I think it would be good to change that. 

I thought of the following options:
- Including the region number automatically in the file naming of the compiled files. 
- Moving the complied files to the folder of the respective rgi region. e.g. `working_dir/per_glacier/RGI60-03/`
- Including both an `input_filesuffix` and an `output_filesuffix` keyword, instead of only
'filesuffix'.

Feel free to post other ideas/preferences :)

**Comment by fmaussion** [comment]
Thanks for the report! I think this is getting quite edgecase, because the normal way to do that would be to have two working directories (one for each RGI region). Funny enough, I independently wrote this recommendation here this morning: https://docs.oggm.org/en/latest/practicalities.html#run-per-rgi-region-not-globally

But OK, let's see what we can do:

> Including the region number automatically in the file naming of the compiled files.

No, because this is redundant with the normal workflow which is to have a working directory of the name of the RGI region. But, more importantly, this solves only this one problem and not another that people might have if they use sub regions for example.

> Moving the complied files to the folder of the respective rgi region. e.g. working_dir/per_glacier/RGI60-03/

Same as above, this is not general enough

> Including both an input_filesuffix and an output_filesuffix keyword, instead of only 'filesuffix'.

Yeah, maybe this. But I'd like the default to be unchanged, i.e. `filesuffix` should continue to exist, and `input_filesuffix` and `output_filesuffix` should default to `filesuffix` when not set. When only `output_filesuffix`  is not set, it should default to `input_filesuffix` 

**Note that** there is already a way to be entirely flexible with output files, thanks to the `path` kwarg. Per default the path is chosen by OGGM, but you can set it to your own path and do whatever suits you:

https://github.com/OGGM/oggm/blob/8a86afae900451b5361c5f08fa802ab875591216/oggm/utils/_workflow.py#L642-L645

**Comment by anoukvlug** [comment]
That is indeed funny that you wrote that this morning :) I didn't see read that yet.  I recently decided sort my simulation by experiment type in a folder, because a different folder for each region is anyway automatically generated within the per_glacier folder. Maybe I should change that.

Anyway, the third option makes sense to me. Though before making a PR for that I will try how convenient things will go when just using the flexible path option :)
