### ISSUE TITLE
Where did oggm calculate the fl.flux?

### ISSUE THREAD

**Issue by Keeptg** [OGGM/oggm#762]
Hello,
I'm trying using oggm to create a new centerline. I transplant most of oggm's original code in my method. And I want my code as consistent as possible with the original one. I guess the method with which oggm add flux in `inversion_flowlines.pkl` is in `oggm.core.centerlines` module, but I can't find how and in where. It has puzzled me for hours. Sorry for bothering you with this small question, but I do very need this now.
Thanks!

**Comment by fmaussion** [comment]
Yes, since the "multiple mu* per glacier" change the code has become quite complex, I agree ;-).

For the flux, first we need the "apparent mass-balance" which in OGGM is computed at the same time as the mass-balance calibration (because we use the equilibrium assumption):

https://github.com/OGGM/oggm/blob/fec5616fe8887a84f06f7ba4826dcff29e2e685f/oggm/core/climate.py#L1181-L1187

And so the actual flux is computed by the centerline objects:

https://github.com/OGGM/oggm/blob/fec5616fe8887a84f06f7ba4826dcff29e2e685f/oggm/core/centerlines.py#L217

It seems to be quite tricky what you are doing, don't hesitate to share your code if you have doubts!
