### ISSUE TITLE
TANDEM download should not check for credentials if file is already downloaded 

### ISSUE THREAD

**Issue by fmaussion** [OGGM/oggm#779]
With the current solution, OGGM expects a credentials file although the file is already downloaded, typically on cluster. 

I don't know what's best do do in this case: possibly turn the credential errors into warnings.

@TimoRoth could you have a look?

**Comment by TimoRoth** [comment]
I've been looking at this and it's a surprisingly difficult problem to solve cleanly.

My current idea that seems cleanest is to first try to "download" the file without providing any credentials, and then when that fails actually demand the credentials.
That's quite ugly though, and since it will be a problem with all future downloads that need credentials, I'd much rather solve this at a lower level, which might require a bit of restructuring.
