### ISSUE TITLE
oggm_mb_above_z

### ISSUE THREAD

**Issue by peltoglacier** [OGGM/oggm#800]
I am not clear on how exactly 'oggm_mb_above_z' is defined
When I call: 
`ds.oggm_mb_above_z`
the description cuts off at " Mass-balance cumulated above the altitude of the point, henc..."
I'm not sure of how to display the rest of the description.

Also, I presume oggm_mb_above_z is only shipped with preprocessing level 3, is it from the default mass balance model? Which is the multiple flow line mass balance model?

**Comment by fmaussion** [comment]
> the description cuts off at " Mass-balance cumulated above the altitude of the point, henc..."
> I'm not sure of how to display the rest of the description.

With `ds.oggm_mb_above_z.description`. It reads: 

"Mass-balance cumulated above the altitude of the point, hence in unit of flux. Note that it is a coarse approximation of the real flux. The mass-balance model is a calibrated temperature index model like OGGM." 

So it's really quite crude, as all points above the altitude considered are contributing to the flux (i.e. it is not taking tributaries into account).

> Also, I presume oggm_mb_above_z is only shipped with preprocessing level 3, is it from the default mass balance model? Which is the multiple flow line mass balance model?

Good question! It is the standard OGGM temperature index mass-balance model, but slightly re-calibrated for this purpose: so that the 2D distributed mass-balance of the glacier is equal to 0. In practice, it is going to be quite close to (but not equal to) the OGGM flowline MB model.
