### ISSUE TITLE
run_prepro_levels is broken

### ISSUE THREAD

**Issue by matthiasdusch** [OGGM/oggm#964]
#957 broke `run_prepro_levels` with:
https://github.com/OGGM/oggm/blob/be4f1186ecb408e101e9a2aa96d7e560b1fa01ec/oggm/workflow.py#L331-L335

Outlines were kept between different DEMs and now there is no new GDir initiated.

Probably need to delete the outlines between every DEM

**Comment by fmaussion** [comment]
I'm not very happy with #957 either.

I did it so because it allows to start from a DEM prepro dir, and then re-open the gdirs with `init_glacier_regions` without triggering a DEM generation. 

Now I believe that the *true* problem is that `init_glacier_regions` does two things: 
- preparing the glacier directories
- processing the DEMs (call `define_glacier_region` on the directories that are not OK)

It was a design error. In hindcast, #957 was probably  a design error since `init_glacier_regions` should actually deliver gdirs with proper DEMs in them...

The best way forward would be to rethink the `init_glacier_regions` logic, but it will be very hard to do so in a backwards compatible manner...

**Comment by fmaussion** [comment]
> Probably need to delete the outlines between every DEM

This, or bypass `init_glacier_regions` entirely. It's only a wrapper anyway
